Repository 2023-AlphaProject/iBelieveSurvey_backend, pull requests merged in 2023-05, with the labels that each got.

#44 [RELEASE] 230513 survey 모델 수정
  webapp/gifticon/models/surveyGifticon.py
  webapp/survey/admin/surveyAdmin.py
  webapp/survey/migrations/0003_survey_started_at.py
  webapp/survey/migrations/0004_remove_survey_status_survey_is_awarded_and_more.py
  webapp/survey/models/survey.py
  webapp/survey/serializers/surveyRetrieveSerializer.py
  webapp/survey/serializers/surveySerializer.py
  webapp/survey/views/surveyRetrieveUpdateDeleteAPIView.py
Labels: release

#45 Hotfix/requirements
  requirements.txt
  test.txt
Labels: fix

#46 [RELEASE] hotfix for requirements
  requirements.txt
  test.txt
Labels: release

#47 hotfix: remove unused import
  webapp/gifticon/models/surveyGifticon.py
Labels: fix

#49 fix: 설문 끝나는 시간이 현재 시간보다 빠를 수 없도록 예외 처리
  test.txt
  webapp/gifticon/models/surveyGifticon.py
  webapp/survey/models/survey.py
Labels: fix

#50 [feature] survey에서 filter 적용
  requirements.txt
  webapp/config/settings/base.py
  webapp/requirements.txt
  webapp/survey/migrations/0005_alter_survey_options.py
  webapp/survey/migrations/0006_alter_survey_options.py
  webapp/survey/models/survey.py
  webapp/survey/serializers/surveyRetrieveSerializer.py
  webapp/survey/serializers/surveySerializer.py
  webapp/survey/views/surveyAPIView.py
Labels: feature

#51 [feat] base pagination 설정
  webapp/config/pagination.py
  webapp/config/settings/base.py
Labels: feature, chore

#56 hotfix: user model
  .vscode/settings.json
  webapp/config/settings/base.py
  webapp/requirements.txt
  webapp/user/migrations/0005_remove_user_id_alter_user_email.py
  webapp/user/models/user.py
Labels: fix

#59 feat: build command 수정
  webapp/cart/models.py
  webapp/cart/serializers/cartSerializers.py
  webapp/cart/urls.py
  webapp/cart/views/cartDetailAPIView.py
  webapp/cart/views/cartListAPIView.py
  webapp/config/urls.py
  webapp/order/views/__init__.py
  webapp/order/views/orderAPIView.py
  webapp/template/management/commands/template_objs_in_db.py
Labels: feature

#62 feat: customize cart admin, views, urls & modify survey views, urls
  webapp/cart/admin/cartAdmin.py
  webapp/cart/migrations/0003_alter_cart_survey_alter_cart_template.py
  webapp/cart/migrations/0004_alter_cart_survey_alter_cart_template.py
  webapp/cart/models.py
  webapp/cart/serializers/cartSerializers.py
  webapp/cart/urls.py
  webapp/cart/views/cartDetailAPIView.py
  webapp/cart/views/cartListAPIView.py
  webapp/config/urls.py
  webapp/requirements.txt
  webapp/survey/urls.py
  webapp/survey/views/surveyRetrieveUpdateDeleteAPIView.py
  webapp/user/migrations/0003_alter_user_email.py
Labels: feature

#64 Feature/kakao pay
  .gitignore
  webapp/cart/models.py
  webapp/cart/urls.py
  webapp/config/settings/base.py
  webapp/config/urls.py
  webapp/payment/__init__.py
  webapp/payment/admin.py
  webapp/payment/apps.py
  webapp/payment/migrations/__init__.py
  webapp/payment/models.py
  webapp/payment/serializers/KakaoPaySerializer.py
  webapp/payment/serializers/__init__.py
  webapp/payment/tests.py
  webapp/payment/urls.py
  webapp/payment/views/KakaoPayAPI.py
  webapp/payment/views/__init__.py
  webapp/survey/migrations/0003_survey_is_paid.py
  webapp/user/migrations/0003_alter_user_email.py
Labels: feature

#66 fix: survey model 수정 및 관련 로직 수정
  webapp/survey/migrations/0003_remove_survey_is_awarded_remove_survey_is_idle_and_more.py
  webapp/survey/models/survey.py
  webapp/survey/serializers/surveyRetrieveSerializer.py
  webapp/survey/serializers/surveySerializer.py
  webapp/survey/views/surveyAPIView.py
  webapp/survey/views/surveyRetrieveUpdateDeleteAPIView.py
Labels: fix

#78 feat: cart serializer 수정 & template serializer 수정
  webapp/cart/serializers/cartSerializers.py
  webapp/template/serializers/templateSerializer.py
Labels: feature
