Repository 2023-AlphaProject/iBelieveSurvey_backend, pull requests merged in 2023-03, with the labels that each got.

#9 feat: swagger 테스트 view, url 수정
  webapp/config/urls.py
  webapp/survey/urls.py
  webapp/survey/views.py
Labels: fix

#12 feat: 카테고리 모델 생성
  webapp/survey/admin.py
  webapp/survey/admin/__init__.py
  webapp/survey/admin/category_admin.py
  webapp/survey/admin/survey_admin.py
  webapp/survey/migrations/0002_alter_survey_options_alter_survey_table.py
  webapp/survey/migrations/0003_category_alter_survey_data_alter_survey_thumbnail_and_more.py
  webapp/survey/migrations/0004_remove_category_created_at_and_more.py
  webapp/survey/models/__init__.py
  webapp/survey/models/category.py
  webapp/survey/models/survey.py
  webapp/survey/serializers/__init__.py
  webapp/survey/serializers/survey_serializer.py
  webapp/survey/urls.py
  webapp/survey/views/__init__.py
  webapp/survey/views/survey_list_apiview.py
Labels: feature

#15 feat: survey crud
  webapp/config/exceptions/__init__.py
  webapp/config/exceptions/handler.py
  webapp/config/settings/base.py
  webapp/config/urls.py
  webapp/manage.py
  webapp/survey/admin/__init__.py
  webapp/survey/admin/categoryAdmin.py
  webapp/survey/admin/surveyAdmin.py
  webapp/survey/migrations/0005_alter_survey_data.py
  webapp/survey/models/category.py
  webapp/survey/models/survey.py
  webapp/survey/serializers/__init__.py
  webapp/survey/serializers/surveyRetrieveSerializer.py
  webapp/survey/serializers/surveySerializer.py
  webapp/survey/serializers/survey_serializer.py
  webapp/survey/urls.py
  webapp/survey/views/__init__.py
  webapp/survey/views/surveyAPIView.py
  webapp/survey/views/surveyRetrieveAPIView.py
  webapp/survey/views/survey_list_apiview.py
  webapp/user/__init__.py
  webapp/user/admin.py
  webapp/user/apps.py
  webapp/user/migrations/__init__.py
  webapp/user/models/__init__.py
  webapp/user/models/user.py
  webapp/user/tests.py
  webapp/user/urls.py
  webapp/user/views/__init__.py
  webapp/user/views/user_view.py
Labels: feature, chore, fix, refactor

#17 Feature/kakao login
  .gitignore
  webapp/Dockerfile
  webapp/config/settings/base.py
  webapp/config/urls.py
  webapp/survey/migrations/0001_initial.py
  webapp/survey/migrations/0002_alter_survey_options_alter_survey_table.py
  webapp/survey/migrations/0003_category_alter_survey_data_alter_survey_thumbnail_and_more.py
  webapp/survey/migrations/0004_remove_category_created_at_and_more.py
  webapp/survey/migrations/0005_alter_survey_data.py
  webapp/survey/models/survey.py
  webapp/user/__init__.py
  webapp/user/admin.py
  webapp/user/apps.py
  webapp/user/models/__init__.py
  webapp/user/models/user.py
  webapp/user/tests.py
  webapp/user/urls.py
  webapp/user/views/__init__.py
  webapp/user/views/kakaoUserView.py
Labels: feature

#25 [FEAT] survey 상태가 시작전 (IDLE)이때만 update 할 수 있도록 설정
  webapp/survey/urls.py
  webapp/survey/views/__init__.py
  webapp/survey/views/surveyRetrieveAPIView.py
  webapp/survey/views/surveyRetrieveUpdateDeleteAPIView.py
Labels: feature, fix
