Repository 2023-AlphaProject/iBelieveSurvey_backend, pull requests merged in 2023-04, with the labels that each got.

#32 chore: set git actions
  .github/workflows/main.yml
Labels: chore

#31 Chore: 배포환경분리
  docker-compose.production.yml
  webapp/Dockerfile.production
  webapp/config/asgi.py
  webapp/config/settings/base.py
  webapp/config/settings/production.py
  webapp/config/wsgi.py
  webapp/docker-entrypoint.production.sh
  webapp/user/models/user.py
Labels: chore

#36 chore: git action을 이용해 CI/CD 구축
  .github/workflows/main.yml
  webapp/config/settings/base.py
Labels: chore, build

#35 fix: accept theirs to resolve conflicts
  webapp/participant/models/__init__.py
  webapp/participant/models/participant.py
  webapp/user/models/user.py
Labels: fix

#40 [ RELEASE]: 배포환경 swagger
  webapp/config/urls.py
  webapp/participant/models/__init__.py
  webapp/participant/models/participant.py
  webapp/user/migrations/0004_alter_user_gender.py
  webapp/user/models/user.py
Labels: build
