Repository 2023-AlphaProject/iBelieveSurvey_backend, pull requests merged in 2023-06, with the labels that each got.

#83 Feature/survey permissions
  webapp/config/exceptions/handler.py
  webapp/survey/permissions.py
  webapp/survey/serializers/hiddenEndSurveySerializer.py
  webapp/survey/serializers/notHiddenEndSurveySerializer.py
  webapp/survey/serializers/surveyRetrieveSerializer.py
  webapp/survey/serializers/surveySerializer.py
  webapp/survey/views/surveyAPIView.py
  webapp/survey/views/surveyRetrieveUpdateDeleteAPIView.py
Labels: feature

#82 feat: participant views 예외처리, serializer 수정
  webapp/participant/models/participant.py
  webapp/participant/serializers/participantSerializer.py
  webapp/participant/tests.py
  webapp/participant/views/participantDetailAPIView.py
  webapp/participant/views/participantListAPIView.py
  webapp/user/models/user.py
  webapp/user/serializers/UserSerializer.py
  webapp/user/serializers/__init__.py
  webapp/user/serializers/userSerializer.py
  webapp/user/views/userAPIView.py
Labels: feature

#84 feat: cart views 예외처리, model, serializer 수정
  webapp/cart/admin/cartAdmin.py
  webapp/cart/migrations/0003_alter_cart_quantity.py
  webapp/cart/models/cart.py
  webapp/cart/serializers/__init__.py
  webapp/cart/serializers/cartDetailSerailizer.py
  webapp/cart/serializers/cartListSerializer.py
  webapp/cart/serializers/cartSerializers.py
  webapp/cart/views/cartDetailAPIView.py
  webapp/cart/views/cartListAPIView.py
Labels: feature

#86 Feature/winning percentage ordering
  webapp/cart/migrations/0004_alter_cart_survey_alter_cart_template.py
  webapp/cart/models/cart.py
  webapp/participant/admin/participantAdmin.py
  webapp/survey/models/survey.py
  webapp/survey/serializers/hiddenEndSurveySerializer.py
  webapp/survey/serializers/notHiddenEndSurveySerializer.py
  webapp/survey/serializers/surveyRetrieveSerializer.py
  webapp/survey/serializers/surveySerializer.py
  webapp/survey/views/surveyAPIView.py
Labels: feature

#87 feat: cronAssignReceiver. 1분마다 order객체 receiver필드에 participant객체 주입하는 로직
  docker-compose.yml
  webapp/Dockerfile
  webapp/cart/migrations/0001_initial.py
  webapp/cart/migrations/0002_initial.py
  webapp/cart/migrations/0003_alter_cart_quantity.py
  webapp/cart/migrations/0004_alter_cart_survey_alter_cart_template.py
  webapp/cart/views/cartDetailAPIView.py
  webapp/cart/views/cartListAPIView.py
  webapp/config/settings/base.py
  webapp/config/urls.py
  webapp/order/admin.py
  webapp/order/admin/orderAdmin.py
  webapp/order/cronAssignReceiver.py
  webapp/order/migrations/0001_initial.py
  webapp/order/migrations/0002_initial.py
  webapp/order/migrations/0003_initial.py
  webapp/order/models/order.py
  webapp/order/serializers/__init__.py
  webapp/order/serializers/orderSerializer.py
  webapp/order/urls.py
  webapp/order/views.py
  webapp/order/views/__init__.py
  webapp/order/views/orderAPIView.py
  webapp/order/views/orderDetailAPIView.py
  webapp/order/views/orderListAPIView.py
  webapp/participant/admin/participantAdmin.py
  webapp/participant/migrations/0001_initial.py
  webapp/participant/migrations/0002_initial.py
  webapp/participant/migrations/0003_initial.py
  webapp/participant/views/participantDetailAPIView.py
  webapp/participant/views/participantListAPIView.py
  webapp/payment/views/KakaoPaySuccess.py
  webapp/requirements.txt
  webapp/survey/migrations/0001_initial.py
  webapp/survey/migrations/0002_initial.py
  webapp/survey/serializers/surveyRetrieveSerializer.py
  webapp/template/migrations/0001_initial.py
  webapp/template/migrations/0002_template_product_detail_url.py
  webapp/template/migrations/0003_alter_template_gift_sent_count.py
  webapp/user/migrations/0001_initial.py
Labels: feature

#89 Feature/show receiver from survey
  webapp/survey/serializers/hiddenEndSurveySerializer.py
  webapp/survey/serializers/notHiddenEndSurveySerializer.py
  webapp/user/models/user.py
  webapp/user/serializers/__init__.py
  webapp/user/serializers/receiverSerializer.py
Labels: feature

#90 Feat/command refact
  webapp/cart/migrations/0001_initial.py
  webapp/cart/migrations/0002_initial.py
  webapp/cart/models/cart.py
  webapp/cart/serializers/cartDetailSerailizer.py
  webapp/cart/serializers/cartListSerializer.py
  webapp/cart/urls.py
  webapp/cart/views/__init__.py
  webapp/cart/views/cronSendGiftAPIView.py
  webapp/config/settings/base.py
  webapp/config/settings/production.py
  webapp/order/cronAssignReceiver.py
  webapp/order/migrations/0001_initial.py
  webapp/order/migrations/0002_initial.py
  webapp/order/urls.py
  webapp/order/views/orderDetailAPIView.py
  webapp/participant/migrations/0001_initial.py
  webapp/participant/migrations/0002_initial.py
  webapp/participant/migrations/0003_initial.py
  webapp/survey/migrations/0001_initial.py
  webapp/survey/migrations/0002_initial.py
  webapp/template/management/commands/template_objs_in_db.py
  webapp/template/migrations/0001_initial.py
  webapp/user/migrations/0001_initial.py
  webapp/user/views/kakaoUserView.py
Labels: fix

#91 Chore/swagger api
  webapp/cart/urls.py
  webapp/cart/views/__init__.py
  webapp/cart/views/cronSendGiftAPIView.py
  webapp/config/settings/base.py
  webapp/config/urls.py
  webapp/order/serializers/__init__.py
  webapp/order/serializers/orderSerializer.py
  webapp/order/urls.py
  webapp/order/views/__init__.py
  webapp/order/views/orderDetailAPIView.py
  webapp/order/views/orderListAPIView.py
  webapp/participant/views/participantDetailAPIView.py
  webapp/payment/views/KakaoPayAPI.py
  webapp/payment/views/KakaoPaySuccess.py
  webapp/survey/views/surveyAPIView.py
  webapp/survey/views/surveyRetrieveUpdateDeleteAPIView.py
  webapp/template/admin.py
  webapp/template/views.py
  webapp/template/views/templateViewSet.py
Labels: feature, chore, fix, release

#92 chore: s3 연동을 위한 설정
  webapp/config/settings/base.py
  webapp/config/storages.py
  webapp/requirements.txt
  webapp/survey/views/surveyAPIView.py
  webapp/survey/views/surveyRetrieveUpdateDeleteAPIView.py
  webapp/user/models/user.py
  webapp/user/views/kakaoUserView.py
Labels: chore, release

#94 feat: 테스트를 위한 크론 주기 재설정
  webapp/config/settings/base.py
Labels: test

#96 Chore/s3: s3 세팅 재설정 및 환경변수화 & 그에 따른 survey views 수정
  webapp/config/settings/base.py
  webapp/survey/views/surveyAPIView.py
  webapp/survey/views/surveyRetrieveUpdateDeleteAPIView.py
Labels: fix

#99 test: image필드 저장 로직 테스트
  webapp/config/settings/base.py
  webapp/config/settings/local.py
  webapp/config/settings/production.py
  webapp/requirements.txt
  webapp/survey/migrations/0003_alter_survey_thumbnail.py
  webapp/survey/migrations/0004_alter_survey_writer.py
  webapp/survey/models/survey.py
  webapp/survey/views/surveyAPIView.py
  webapp/survey/views/surveyRetrieveUpdateDeleteAPIView.py
  webapp/user/models/user.py
  webapp/user/views/kakaoUserView.py
Labels: test

#102 fix: started_at과 end_at 필드 일치시키기
  webapp/survey/migrations/0004_alter_survey_started_at.py
  webapp/survey/models/survey.py
Labels: fix

#106 fix: datetime과 date를 비교할 수 있도록 처리
  webapp/payment/views/KakaoPayAPI.py
  webapp/payment/views/KakaoPaySuccess.py
  webapp/survey/models/survey.py
Labels: fix

#107 fix: 특정 survey에 해당하는 모든 cart객체들 반환하도록 수정 & permission 해제
  webapp/cart/views/cartDetailAPIView.py
  webapp/cart/views/cartListAPIView.py
Labels: fix

#113 Feature/receiver product
  webapp/config/settings/base.py
  webapp/survey/models/survey.py
  webapp/survey/serializers/hiddenEndSurveySerializer.py
  webapp/survey/serializers/notHiddenEndSurveySerializer.py
Labels: feature, fix

#114 Fix/survey serializer
  webapp/participant/views/participantDetailAPIView.py
  webapp/participant/views/participantListAPIView.py
  webapp/user/views/kakaoUserView.py
Labels: fix

#133 fix: 당첨확률 높은 순과 마감 임박 순에서 진행 중인 설문만 filtering 후 ordering 적용
  webapp/survey/views/surveyAPIView.py
Labels: fix
